### PR TITLE
Implemented methods in the testing jcr-mock module:

### PR DESCRIPTION
**Pull request by danilocugia**
This changes allow the following operations:
- Add mixin to a node
- Get node index
- Get mixin node types
- Node repositioning (node.orderBefore)
- Remove mixin
- Move node

### CODE REVIEW

**Comment by stefanseifert** [comment]
thanks for your contribution!

can you file an issue in the Sling JIRA for this and add a link to this PR?
https://issues.apache.org/jira/browse/SLING
this is the standard procedure.

and we will need some unit tests for the new behavior as well.

**Comment by danilocugia** [comment]
Hi Stefan,

ok I will. I didn't know about the procedure. Thanks for letting me know.

Regards,

Danilo

On 2 February 2016 at 14:38, Stefan Seifert notifications@github.com
wrote:

> thanks for your contribution!
> 
> can you file an issue in the Sling JIRA for this and add a link to this PR?
> https://issues.apache.org/jira/browse/SLING
> this is the standard procedure.
> 
> and we will need some unit tests for the new behavior as well.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/apache/sling/pull/121#issuecomment-178602277.

## 

Email: danilo.cugia@gmail.com
LinkedIn: https://uk.linkedin.com/in/danilocugia

**Comment by danilocugia** [comment]
https://issues.apache.org/jira/browse/SLING-5478

I'm going to write some test cases as soon as I can.

**Comment by danilocugia** [comment]
Hi @stefanseifert I've committed a bugfix plus all the test cases to cover the new implemented methods. Let me know if there is something I need to change.

Thanks,
Danilo

**Comment by rombert** [comment]
With the upcoming migration to git this repository will be deleted. If the pull request contains data that should be re-submitted I suggest that you save the changes locally and resubmit them after the migration, which will likely happen on Monday the 9th of October.

**Pull request closed without merging**
