### PR TITLE
SLING-3776 JsonRendererServlet should provide a way to list children as ...

### PR DESCRIPTION
**Pull request by visiongeist**
Adding an "array" selector will print the children of the node under the key "_children" and adds its key as a "_name" attribute. The wordings would need to be improved.

I did the implementation of it only in the servlet, some parts may be possible to be moved to JSONObject though imho I think it belongs rather to the servlet because it is for pure formatting.

### CODE REVIEW

**Comment by bdelacretaz** [comment]
Could you add automated tests? Ideally alongside the  https://svn.apache.org/repos/asf/sling/trunk/launchpad/integration-tests/src/main/java/org/apache/sling/launchpad/webapp/integrationtest/JsonRenderingTest.java integration test. The ../integration-tests/README.txt explains how to run those tests.

**Comment by visiongeist** [comment]
I'm on it

**Comment by rombert** [comment]
With the upcoming migration to git this repository will be deleted. If the pull request contains data that should be re-submitted I suggest that you save the changes locally and resubmit them after the migration, which will likely happen on Monday the 9th of October.

**Comment by bdelacretaz** [comment]
The `.harray` selector is implemented and documented at https://sling.apache.org/documentation/bundles/rendering-content-default-get-servlets.html so I think this can be safely deleted.

**Pull request closed without merging**
