### PR TITLE
SLING-2792: Typo in Javadoc link of PersistableValueMap

### PR DESCRIPTION
**Pull request by lukaseder**

### CODE REVIEW

**Comment by rombert** [comment]
@lukaseder  - the Jira issue has been resolved, can you please close the pull request?

**Comment by lukaseder** [comment]
Heh, 2013... Those were the days :)
Hope you're doing great!

**Comment by rombert** [comment]
Yes, 2013 was a looong time ago :-) Yes, doing just fine now - and a little end-of-year cleanup on the Sling pull requests

**Comment by lukaseder** [comment]
Someone has to do it

**Pull request closed without merging**
