### PR TITLE
Support CGLIB enhanced classes for Mockito based service mocks

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by rombert** [comment]
It would be great to have a SLING jira issue opened to discuss this enhancement, including how to reproduce the problem :-)

**Comment by rombert** [comment]
Ah, so there is SLING-4813 ... please include the issue id in the commit title to make sure the links are created.

Can you also include a minimal unit test 'proving' that the problem is solved?

**Comment by ghost** [comment]
yes, I have no time for it. I try to do it soon, but currently have to meet some deadline...

**Comment by ghost** [comment]
done

**Pull request closed without merging**
