### PR TITLE
SLING-5948 Support Streaming.

### PR DESCRIPTION
**Pull request by ieb**
Creating pull request to trigger builds by CI and Travis. See issue for details. Will commit to SVN if all ok.

### CODE REVIEW

**Comment by ieb** [comment]
Jenkins CI branch build which uses JDK 1.7 passes upto the point of launchpad/builder which required JDK 1.8.  Waiting for Travis to complete before comitting

**Comment by ieb** [comment]
Travis CI failed on JDK 7 at launchpad also. JDK 8 Ok.

**Comment by kwin** [comment]
@ieb This has been fixed, can you close this PR?

**Comment by ieb** [comment]
incorporated in the Sling code base. Closing.

**Pull request closed without merging**
